#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* Swagger UI
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGLoginRequest
@end

@interface SWGLoginRequest : SWGObject

/*  
 */
@property(nonatomic) NSString* mobileNum;
/*  
 */
@property(nonatomic) NSString* password;

@end
